package model;
// Generated 07/08/2018 13:28:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
)
public class Cidade  implements java.io.Serializable {


     private int idCidade;
     private String nome;
     private int idEstado;
     private char inativo;

    public Cidade() {
    }

    public Cidade(int idCidade, String nome, int idEstado, char inativo) {
       this.idCidade = idCidade;
       this.nome = nome;
       this.idEstado = idEstado;
       this.inativo = inativo;
    }
   
     @Id 

    
    @Column(name="id_cidade", nullable=false)
    public int getIdCidade() {
        return this.idCidade;
    }
    
    public void setIdCidade(int idCidade) {
        this.idCidade = idCidade;
    }

    
    @Column(name="nome", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }




}


