package model;
// Generated 07/08/2018 09:35:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,schema="public"
)
public class Cidade  implements java.io.Serializable {


     private int idCidade;
     private Estado estado;
     private String nome;
     private char inativo;
     private Set pessoas = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(int idCidade, Estado estado, String nome, char inativo) {
        this.idCidade = idCidade;
        this.estado = estado;
        this.nome = nome;
        this.inativo = inativo;
    }
    public Cidade(int idCidade, Estado estado, String nome, char inativo, Set pessoas) {
       this.idCidade = idCidade;
       this.estado = estado;
       this.nome = nome;
       this.inativo = inativo;
       this.pessoas = pessoas;
    }
   
     @Id 

    
    @Column(name="id_cidade", unique=true, nullable=false)
    public int getIdCidade() {
        return this.idCidade;
    }
    
    public void setIdCidade(int idCidade) {
        this.idCidade = idCidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_estado", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    
    @Column(name="nome", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


