package model;
// Generated 06/08/2018 21:15:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="estado"
    ,schema="public"
    , uniqueConstraints = {@UniqueConstraint(columnNames="nome"), @UniqueConstraint(columnNames="uf")} 
)
public class Estado  implements java.io.Serializable {


     private int idEstado;
     private String nome;
     private String uf;
     private char inativo;
     private Set cidades = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int idEstado, String nome, String uf, char inativo) {
        this.idEstado = idEstado;
        this.nome = nome;
        this.uf = uf;
        this.inativo = inativo;
    }
    public Estado(int idEstado, String nome, String uf, char inativo, Set cidades) {
       this.idEstado = idEstado;
       this.nome = nome;
       this.uf = uf;
       this.inativo = inativo;
       this.cidades = cidades;
    }
   
     @Id 

    
    @Column(name="id_estado", unique=true, nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="nome", unique=true, nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="uf", unique=true, nullable=false, length=2)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


