package model;
// Generated 06/08/2018 21:15:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstoqueId generated by hbm2java
 */
@Embeddable
public class EstoqueId  implements java.io.Serializable {


     private int idEstoque;
     private int idPedido;
     private int idProduto;

    public EstoqueId() {
    }

    public EstoqueId(int idEstoque, int idPedido, int idProduto) {
       this.idEstoque = idEstoque;
       this.idPedido = idPedido;
       this.idProduto = idProduto;
    }
   


    @Column(name="id_estoque", nullable=false)
    public int getIdEstoque() {
        return this.idEstoque;
    }
    
    public void setIdEstoque(int idEstoque) {
        this.idEstoque = idEstoque;
    }


    @Column(name="id_pedido", nullable=false)
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }


    @Column(name="id_produto", nullable=false)
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstoqueId) ) return false;
		 EstoqueId castOther = ( EstoqueId ) other; 
         
		 return (this.getIdEstoque()==castOther.getIdEstoque())
 && (this.getIdPedido()==castOther.getIdPedido())
 && (this.getIdProduto()==castOther.getIdProduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEstoque();
         result = 37 * result + this.getIdPedido();
         result = 37 * result + this.getIdProduto();
         return result;
   }   


}


