package model;
// Generated 07/08/2018 13:28:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FormaPagamento generated by hbm2java
 */
@Entity
@Table(name="forma_pagamento"
)
public class FormaPagamento  implements java.io.Serializable {


     private int idFormaPagamento;
     private String nome;
     private int parcelas;
     private char inativo;
     private Float percDesconto;
     private Float percAcrescimo;

    public FormaPagamento() {
    }


    public FormaPagamento(int idFormaPagamento, String nome, int parcelas, char inativo, Float percDesconto, Float percAcrescimo) {
       this.idFormaPagamento = idFormaPagamento;
       this.nome = nome;
       this.parcelas = parcelas;
       this.inativo = inativo;
       this.percDesconto = percDesconto;
       this.percAcrescimo = percAcrescimo;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_forma_pagamento", nullable=false)
    public int getIdFormaPagamento() {
        return this.idFormaPagamento;
    }
    
    public void setIdFormaPagamento(int idFormaPagamento) {
        this.idFormaPagamento = idFormaPagamento;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="parcelas", nullable=false)
    public int getParcelas() {
        return this.parcelas;
    }
    
    public void setParcelas(int parcelas) {
        this.parcelas = parcelas;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }

    
    @Column(name="perc_desconto")
    public Float getPercDesconto() {
        return this.percDesconto;
    }
    
    public void setPercDesconto(Float percDesconto) {
        this.percDesconto = percDesconto;
    }

    
    @Column(name="perc_acrescimo")
    public Float getPercAcrescimo() {
        return this.percAcrescimo;
    }
    
    public void setPercAcrescimo(Float percAcrescimo) {
        this.percAcrescimo = percAcrescimo;
    }

    @Override
    public String toString() {
        return "FormaPagamento{" + "idFormaPagamento=" + idFormaPagamento + ", nome=" + nome + ", parcelas=" + parcelas + ", inativo=" + inativo + ", percDesconto=" + percDesconto + ", percAcrescimo=" + percAcrescimo + '}';
    }




}


