package model;
// Generated 07/08/2018 13:28:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@PrimaryKeyJoinColumn(name="id_pessoa")
@Table(name="funcionario")
public class Funcionario extends Pessoa implements java.io.Serializable {


    // private int idPessoa;
     private int cpf;
     private Date nascimento;
     private Cargos cargo;
    //private int idCargos;
     //private Pessoa pessoa;

    @ManyToOne
    @JoinColumn(name="id_cargos", nullable=false)
    public Cargos getCargo() 
    {
        return cargo;
    }

    public void setCargo(Cargos cargo) 
    {
        this.cargo = cargo;
    }
     
    /*@Id 
    
    @Column(name="id_pessoa", nullable=false)
    public Pessoa getPessoa() {
        return pessoa;
    }

    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }*/

    public Funcionario() {
        //this.pessoa = new Pessoa();
    }

    public Funcionario(int idPessoa, int cpf, Date nascimento, int idCargos) {
       //this.idPessoa = idPessoa;
       this.cpf = cpf;
       this.nascimento = nascimento;
       // this.idCargos = idCargos;
    }
   

     /*public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }*/

    
    @Column(name="cpf", nullable=false)
    public int getCpf() {
        return this.cpf;
    }
    
    public void setCpf(int cpf) {
        this.cpf = cpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nascimento", nullable=false, length=13)
    public Date getNascimento() {
        return this.nascimento;
    }
    
    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }

    
    /*@Column(name="id_cargos", nullable=false)
    public int getIdCargos() {
        return this.idCargos;
    }
    
    public void setIdCargos(int idCargos) {
        this.idCargos = idCargos;
    }*/
}


