package model;
// Generated 06/08/2018 21:15:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItensPedido generated by hbm2java
 */
@Entity
@Table(name="itens_pedido"
    ,schema="public"
)
public class ItensPedido  implements java.io.Serializable {


     private ItensPedidoId id;
     private Pedido pedido;
     private Produto produto;
     private long quantidade;
     private BigDecimal valorTotal;
     private Set estoques = new HashSet(0);

    public ItensPedido() {
    }

	
    public ItensPedido(ItensPedidoId id, Pedido pedido, Produto produto, long quantidade, BigDecimal valorTotal) {
        this.id = id;
        this.pedido = pedido;
        this.produto = produto;
        this.quantidade = quantidade;
        this.valorTotal = valorTotal;
    }
    public ItensPedido(ItensPedidoId id, Pedido pedido, Produto produto, long quantidade, BigDecimal valorTotal, Set estoques) {
       this.id = id;
       this.pedido = pedido;
       this.produto = produto;
       this.quantidade = quantidade;
       this.valorTotal = valorTotal;
       this.estoques = estoques;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPedido", column=@Column(name="id_pedido", nullable=false) ), 
        @AttributeOverride(name="idProduto", column=@Column(name="id_produto", nullable=false) ) } )
    public ItensPedidoId getId() {
        return this.id;
    }
    
    public void setId(ItensPedidoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pedido", nullable=false, insertable=false, updatable=false)
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_produto", nullable=false, insertable=false, updatable=false)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    
    @Column(name="quantidade", nullable=false, precision=10, scale=0)
    public long getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(long quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valor_total", nullable=false, precision=10)
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itensPedido")
    public Set getEstoques() {
        return this.estoques;
    }
    
    public void setEstoques(Set estoques) {
        this.estoques = estoques;
    }




}


