package model;
// Generated 07/08/2018 09:35:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimentacaoFinanc generated by hbm2java
 */
@Entity
@Table(name="movimentacao_financ"
    ,schema="public"
)
public class MovimentacaoFinanc  implements java.io.Serializable {


     private MovimentacaoFinancId id;
     private Pedido pedido;
     private BigDecimal valor;
     private Date dataVencimento;
     private Date dataQuitacao;
     private Date dataCancelamento;

    public MovimentacaoFinanc() {
    }

	
    public MovimentacaoFinanc(MovimentacaoFinancId id, Pedido pedido, BigDecimal valor, Date dataVencimento) {
        this.id = id;
        this.pedido = pedido;
        this.valor = valor;
        this.dataVencimento = dataVencimento;
    }
    public MovimentacaoFinanc(MovimentacaoFinancId id, Pedido pedido, BigDecimal valor, Date dataVencimento, Date dataQuitacao, Date dataCancelamento) {
       this.id = id;
       this.pedido = pedido;
       this.valor = valor;
       this.dataVencimento = dataVencimento;
       this.dataQuitacao = dataQuitacao;
       this.dataCancelamento = dataCancelamento;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPedido", column=@Column(name="id_pedido", nullable=false) ), 
        @AttributeOverride(name="seq", column=@Column(name="seq", nullable=false) ) } )
    public MovimentacaoFinancId getId() {
        return this.id;
    }
    
    public void setId(MovimentacaoFinancId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pedido", nullable=false, insertable=false, updatable=false)
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    
    @Column(name="valor", nullable=false, precision=10)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_vencimento", nullable=false, length=13)
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_quitacao", length=13)
    public Date getDataQuitacao() {
        return this.dataQuitacao;
    }
    
    public void setDataQuitacao(Date dataQuitacao) {
        this.dataQuitacao = dataQuitacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cancelamento", length=13)
    public Date getDataCancelamento() {
        return this.dataCancelamento;
    }
    
    public void setDataCancelamento(Date dataCancelamento) {
        this.dataCancelamento = dataCancelamento;
    }




}


