package model;
// Generated 06/08/2018 21:15:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MovimentacaoFinancId generated by hbm2java
 */
@Embeddable
public class MovimentacaoFinancId  implements java.io.Serializable {


     private int idPedido;
     private int seq;

    public MovimentacaoFinancId() {
    }

    public MovimentacaoFinancId(int idPedido, int seq) {
       this.idPedido = idPedido;
       this.seq = seq;
    }
   


    @Column(name="id_pedido", nullable=false)
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }


    @Column(name="seq", nullable=false)
    public int getSeq() {
        return this.seq;
    }
    
    public void setSeq(int seq) {
        this.seq = seq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MovimentacaoFinancId) ) return false;
		 MovimentacaoFinancId castOther = ( MovimentacaoFinancId ) other; 
         
		 return (this.getIdPedido()==castOther.getIdPedido())
 && (this.getSeq()==castOther.getSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPedido();
         result = 37 * result + this.getSeq();
         return result;
   }   


}


