package model;
// Generated 07/08/2018 13:28:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.type.descriptor.sql.TinyIntTypeDescriptor;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="pedido"
)
public class Pedido  implements java.io.Serializable {


     private int idPedido;
     private int idCliente;
     private int idVendedor;
     private int idFormaPagamento;
     private Date dataPedido;
     private char tipo;
     private char situacao;
     private BigDecimal valorTotal;
     private BigDecimal desconto;
     private BigDecimal acrescimo;

    public Pedido() {
    }

	
    public Pedido(int idPedido, int idCliente, int idVendedor, int idFormaPagamento, Date dataPedido, char tipo, char situacao, BigDecimal valorTotal) {
        this.idPedido = idPedido;
        this.idCliente = idCliente;
        this.idVendedor = idVendedor;
        this.idFormaPagamento = idFormaPagamento;
        this.dataPedido = dataPedido;
        this.tipo = tipo;
        this.situacao = situacao;
        this.valorTotal = valorTotal;
    }
    public Pedido(int idPedido, int idCliente, int idVendedor, int idFormaPagamento, Date dataPedido, char tipo, char situacao, BigDecimal valorTotal, BigDecimal desconto, BigDecimal acrescimo) {
       this.idPedido = idPedido;
       this.idCliente = idCliente;
       this.idVendedor = idVendedor;
       this.idFormaPagamento = idFormaPagamento;
       this.dataPedido = dataPedido;
       this.tipo = tipo;
       this.situacao = situacao;
       this.valorTotal = valorTotal;
       this.desconto = desconto;
       this.acrescimo = acrescimo;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    @Column(name="id_pedido", nullable=false)
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }

    
    @Column(name="id_cliente", nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="id_vendedor", nullable=false)
    public int getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(int idVendedor) {
        this.idVendedor = idVendedor;
    }

    
    @Column(name="id_forma_pagamento", nullable=false)
    public int getIdFormaPagamento() {
        return this.idFormaPagamento;
    }
    
    public void setIdFormaPagamento(int idFormaPagamento) {
        this.idFormaPagamento = idFormaPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_pedido", nullable=false, length=13)
    public Date getDataPedido() {
        return this.dataPedido;
    }
    
    public void setDataPedido(Date dataPedido) {
        this.dataPedido = dataPedido;
    }

    
    @Column(name="tipo", nullable=false, length=1)
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="situacao", nullable=false, length=1)
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }

    
    @Column(name="valor_total", nullable=false, precision=10)
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    
    @Column(name="desconto", precision=10)
    public BigDecimal getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(BigDecimal desconto) {
        this.desconto = desconto;
    }

    
    @Column(name="acrescimo", precision=10)
    public BigDecimal getAcrescimo() {
        return this.acrescimo;
    }
    
    public void setAcrescimo(BigDecimal acrescimo) {
        this.acrescimo = acrescimo;
    }

}


