package model;
// Generated 06/08/2018 21:15:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="pedido"
    ,schema="public"
)
public class Pedido  implements java.io.Serializable {


     private int idPedido;
     private FormaPagamento formaPagamento;
     private Funcionario funcionario;
     private PessoaJuridica pessoaJuridica;
     private Date dataPedido;
     private char tipo;
     private char situacao;
     private BigDecimal valorTotal;
     private BigDecimal desconto;
     private BigDecimal acrescimo;
     private Set movimentacaoFinancs = new HashSet(0);
     private Set itensPedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int idPedido, FormaPagamento formaPagamento, Funcionario funcionario, PessoaJuridica pessoaJuridica, Date dataPedido, char tipo, char situacao, BigDecimal valorTotal) {
        this.idPedido = idPedido;
        this.formaPagamento = formaPagamento;
        this.funcionario = funcionario;
        this.pessoaJuridica = pessoaJuridica;
        this.dataPedido = dataPedido;
        this.tipo = tipo;
        this.situacao = situacao;
        this.valorTotal = valorTotal;
    }
    public Pedido(int idPedido, FormaPagamento formaPagamento, Funcionario funcionario, PessoaJuridica pessoaJuridica, Date dataPedido, char tipo, char situacao, BigDecimal valorTotal, BigDecimal desconto, BigDecimal acrescimo, Set movimentacaoFinancs, Set itensPedidos) {
       this.idPedido = idPedido;
       this.formaPagamento = formaPagamento;
       this.funcionario = funcionario;
       this.pessoaJuridica = pessoaJuridica;
       this.dataPedido = dataPedido;
       this.tipo = tipo;
       this.situacao = situacao;
       this.valorTotal = valorTotal;
       this.desconto = desconto;
       this.acrescimo = acrescimo;
       this.movimentacaoFinancs = movimentacaoFinancs;
       this.itensPedidos = itensPedidos;
    }
   
     @Id 

    
    @Column(name="id_pedido", unique=true, nullable=false)
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_forma_pagamento", nullable=false)
    public FormaPagamento getFormaPagamento() {
        return this.formaPagamento;
    }
    
    public void setFormaPagamento(FormaPagamento formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vendedor", nullable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente", nullable=false)
    public PessoaJuridica getPessoaJuridica() {
        return this.pessoaJuridica;
    }
    
    public void setPessoaJuridica(PessoaJuridica pessoaJuridica) {
        this.pessoaJuridica = pessoaJuridica;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_pedido", nullable=false, length=13)
    public Date getDataPedido() {
        return this.dataPedido;
    }
    
    public void setDataPedido(Date dataPedido) {
        this.dataPedido = dataPedido;
    }

    
    @Column(name="tipo", nullable=false, length=1)
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="situacao", nullable=false, length=1)
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }

    
    @Column(name="valor_total", nullable=false, precision=10)
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    
    @Column(name="desconto", precision=10)
    public BigDecimal getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(BigDecimal desconto) {
        this.desconto = desconto;
    }

    
    @Column(name="acrescimo", precision=10)
    public BigDecimal getAcrescimo() {
        return this.acrescimo;
    }
    
    public void setAcrescimo(BigDecimal acrescimo) {
        this.acrescimo = acrescimo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedido")
    public Set getMovimentacaoFinancs() {
        return this.movimentacaoFinancs;
    }
    
    public void setMovimentacaoFinancs(Set movimentacaoFinancs) {
        this.movimentacaoFinancs = movimentacaoFinancs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedido")
    public Set getItensPedidos() {
        return this.itensPedidos;
    }
    
    public void setItensPedidos(Set itensPedidos) {
        this.itensPedidos = itensPedidos;
    }




}


