package model;
// Generated 07/08/2018 13:28:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PessoaJuridica generated by hbm2java
 */
@Entity
@PrimaryKeyJoinColumn(name="id_pessoa_juridica")
@Table(name="pessoa_juridica")
public class PessoaJuridica  extends Pessoa implements java.io.Serializable {


     // private int idPessoa;
     private String cnpj;
     private String ie;
     private String fantasia;
     private Date dataCadastro;
     private char tipo;

    public PessoaJuridica() {
    }

	
    public PessoaJuridica(String cnpj, String ie, Date dataCadastro, char tipo) {
        // this.idPessoa = idPessoa;
        this.cnpj = cnpj;
        this.ie = ie;
        this.dataCadastro = dataCadastro;
        this.tipo = tipo;
    }
    public PessoaJuridica(String cnpj, String ie, String fantasia, Date dataCadastro, char tipo) {
       //this.idPessoa = idPessoa;
       this.cnpj = cnpj;
       this.ie = ie;
       this.fantasia = fantasia;
       this.dataCadastro = dataCadastro;
       this.tipo = tipo;
    }
   
    /* @Id 

    
    @Column(name="id_pessoa", nullable=false)
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }*/

    
    @Column(name="cnpj", nullable=false, length=16)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="ie", nullable=false, length=12)
    public String getIe() {
        return this.ie;
    }
    
    public void setIe(String ie) {
        this.ie = ie;
    }

    
    @Column(name="fantasia", length=45)
    public String getFantasia() {
        return this.fantasia;
    }
    
    public void setFantasia(String fantasia) {
        this.fantasia = fantasia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cadastro", nullable=false, length=13)
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    
    @Column(name="tipo", nullable=false, length=1)
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }




}


