package model;
// Generated 06/08/2018 21:15:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PessoaJuridica generated by hbm2java
 */
@Entity
@Table(name="pessoa_juridica"
    ,schema="public"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cnpj"), @UniqueConstraint(columnNames="ie")} 
)
public class PessoaJuridica  implements java.io.Serializable {


     private int idPessoa;
     private Pessoa pessoa;
     private long cnpj;
     private int ie;
     private String fantasia;
     private Date dataCadastro;
     private char tipo;
     private Set pedidos = new HashSet(0);

    public PessoaJuridica() {
    }

	
    public PessoaJuridica(Pessoa pessoa, long cnpj, int ie, Date dataCadastro, char tipo) {
        this.pessoa = pessoa;
        this.cnpj = cnpj;
        this.ie = ie;
        this.dataCadastro = dataCadastro;
        this.tipo = tipo;
    }
    public PessoaJuridica(Pessoa pessoa, long cnpj, int ie, String fantasia, Date dataCadastro, char tipo, Set pedidos) {
       this.pessoa = pessoa;
       this.cnpj = cnpj;
       this.ie = ie;
       this.fantasia = fantasia;
       this.dataCadastro = dataCadastro;
       this.tipo = tipo;
       this.pedidos = pedidos;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pessoa"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_pessoa", unique=true, nullable=false)
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="cnpj", unique=true, nullable=false)
    public long getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(long cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="ie", unique=true, nullable=false)
    public int getIe() {
        return this.ie;
    }
    
    public void setIe(int ie) {
        this.ie = ie;
    }

    
    @Column(name="fantasia", length=45)
    public String getFantasia() {
        return this.fantasia;
    }
    
    public void setFantasia(String fantasia) {
        this.fantasia = fantasia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cadastro", nullable=false, length=13)
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    
    @Column(name="tipo", nullable=false, length=1)
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoaJuridica")
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


