package model;
// Generated 07/08/2018 09:35:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto"
    ,schema="public"
)
public class Produto  implements java.io.Serializable {


     private int idProduto;
     private Unidade unidade;
     private String nome;
     private String descricao;
     private BigDecimal percentualLucro;
     private char inativo;
     private Set itensPedidos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int idProduto, Unidade unidade, String nome, BigDecimal percentualLucro, char inativo) {
        this.idProduto = idProduto;
        this.unidade = unidade;
        this.nome = nome;
        this.percentualLucro = percentualLucro;
        this.inativo = inativo;
    }
    public Produto(int idProduto, Unidade unidade, String nome, String descricao, BigDecimal percentualLucro, char inativo, Set itensPedidos) {
       this.idProduto = idProduto;
       this.unidade = unidade;
       this.nome = nome;
       this.descricao = descricao;
       this.percentualLucro = percentualLucro;
       this.inativo = inativo;
       this.itensPedidos = itensPedidos;
    }
   
     @Id 

    
    @Column(name="id_produto", unique=true, nullable=false)
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_unidade", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao", length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="percentual_lucro", nullable=false, precision=3)
    public BigDecimal getPercentualLucro() {
        return this.percentualLucro;
    }
    
    public void setPercentualLucro(BigDecimal percentualLucro) {
        this.percentualLucro = percentualLucro;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produto")
    public Set getItensPedidos() {
        return this.itensPedidos;
    }
    
    public void setItensPedidos(Set itensPedidos) {
        this.itensPedidos = itensPedidos;
    }




}


