package model;
// Generated 07/08/2018 13:28:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto"
)
public class Produto  implements java.io.Serializable {


     private int idProduto;
     private String nome;
     private String descricao;
     private BigDecimal percentualLucro;
     private char inativo;
     private int idUnidade;

    public Produto() {
    }

	
    public Produto(int idProduto, String nome, BigDecimal percentualLucro, char inativo, int idUnidade) {
        this.idProduto = idProduto;
        this.nome = nome;
        this.percentualLucro = percentualLucro;
        this.inativo = inativo;
        this.idUnidade = idUnidade;
    }
    public Produto(int idProduto, String nome, String descricao, BigDecimal percentualLucro, char inativo, int idUnidade) {
       this.idProduto = idProduto;
       this.nome = nome;
       this.descricao = descricao;
       this.percentualLucro = percentualLucro;
       this.inativo = inativo;
       this.idUnidade = idUnidade;
    }
   
     @Id 

    
    @Column(name="id_produto", nullable=false)
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao", length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="percentual_lucro", nullable=false, precision=3)
    public BigDecimal getPercentualLucro() {
        return this.percentualLucro;
    }
    
    public void setPercentualLucro(BigDecimal percentualLucro) {
        this.percentualLucro = percentualLucro;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }

    
    @Column(name="id_unidade", nullable=false)
    public int getIdUnidade() {
        return this.idUnidade;
    }
    
    public void setIdUnidade(int idUnidade) {
        this.idUnidade = idUnidade;
    }




}


