package model;
// Generated 07/08/2018 13:28:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Unidade generated by hbm2java
 */
@Entity
@Table(name="unidade"
)
public class Unidade  implements java.io.Serializable {


     private int idUnidade;
     private String nome;
     private String sigla;
     private char inativo;

    public Unidade() {
    }

    public Unidade(int idUnidade, String nome, String sigla, char inativo) {
       this.idUnidade = idUnidade;
       this.nome = nome;
       this.sigla = sigla;
       this.inativo = inativo;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_unidade", nullable=false)
    public int getIdUnidade() {
        return this.idUnidade;
    }
    
    public void setIdUnidade(int idUnidade) {
        this.idUnidade = idUnidade;
    }

    
    @Column(name="nome", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sigla", nullable=false, length=3)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }




}


