package model;
// Generated 06/08/2018 21:15:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unidade generated by hbm2java
 */
@Entity
@Table(name="unidade"
    ,schema="public"
)
public class Unidade  implements java.io.Serializable {


     private int idUnidade;
     private String nome;
     private String sigla;
     private char inativo;
     private Set produtos = new HashSet(0);

    public Unidade() {
    }

	
    public Unidade(int idUnidade, String nome, String sigla, char inativo) {
        this.idUnidade = idUnidade;
        this.nome = nome;
        this.sigla = sigla;
        this.inativo = inativo;
    }
    public Unidade(int idUnidade, String nome, String sigla, char inativo, Set produtos) {
       this.idUnidade = idUnidade;
       this.nome = nome;
       this.sigla = sigla;
       this.inativo = inativo;
       this.produtos = produtos;
    }
   
     @Id 

    
    @Column(name="id_unidade", unique=true, nullable=false)
    public int getIdUnidade() {
        return this.idUnidade;
    }
    
    public void setIdUnidade(int idUnidade) {
        this.idUnidade = idUnidade;
    }

    
    @Column(name="nome", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sigla", nullable=false, length=3)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


