package model;
// Generated 07/08/2018 13:28:03 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import model.util.Criptografia;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

    public static String senhaDefault = "********";

    private int idUsuario;
    private Integer idPessoa;
    private int nivelAcesso;
    private String senha;
    private String username;
    private char inativo;

    public Usuario() {
    }

    public Usuario(int idUsuario, int nivelAcesso, String senha, String username, char inativo) {
        this.idUsuario = idUsuario;
        this.nivelAcesso = nivelAcesso;
        this.senha = senha;
        this.username = username;
        this.inativo = inativo;
    }

    public Usuario(int idUsuario, Integer idPessoa, int nivelAcesso, String senha, String username, char inativo) {
        this.idUsuario = idUsuario;
        this.idPessoa = idPessoa;
        this.nivelAcesso = nivelAcesso;
        this.senha = senha;
        this.username = username;
        this.inativo = inativo;
    }

    @Id

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_usuario", nullable = false)
    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Column(name = "id_pessoa")
    public Integer getIdPessoa() {
        return this.idPessoa;
    }

    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }

    @Column(name = "nivel_acesso", nullable = false)
    public int getNivelAcesso() {
        return this.nivelAcesso;
    }

    public void setNivelAcesso(int nivelAcesso) {
        this.nivelAcesso = nivelAcesso;
    }

    @Column(name = "senha", nullable = false, length = 50)
    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = Criptografia.criptografar(senha);
    }

    @Column(name = "username", nullable = false, length = 60)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "inativo", nullable = false, length = 1)
    public char getInativo() {
        return this.inativo;
    }

    public void setInativo(char inativo) {
        this.inativo = inativo;
    }

}
