package model;
// Generated 06/08/2018 21:15:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class Usuario  implements java.io.Serializable {


     private int idPessoa;
     private Funcionario funcionario;
     private int nivelAcesso;
     private String senha;
     private String username;
     private char inativo;

    public Usuario() {
    }

    public Usuario(Funcionario funcionario, int nivelAcesso, String senha, String username, char inativo) {
       this.funcionario = funcionario;
       this.nivelAcesso = nivelAcesso;
       this.senha = senha;
       this.username = username;
       this.inativo = inativo;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="funcionario"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_pessoa", unique=true, nullable=false)
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    
    @Column(name="nivel_acesso", nullable=false)
    public int getNivelAcesso() {
        return this.nivelAcesso;
    }
    
    public void setNivelAcesso(int nivelAcesso) {
        this.nivelAcesso = nivelAcesso;
    }

    
    @Column(name="senha", nullable=false, length=50)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="username", unique=true, nullable=false, length=60)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }




}


