package model;
// Generated 07/08/2018 09:35:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Funcionario funcionario;
     private int nivelAcesso;
     private String senha;
     private String username;
     private char inativo;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, int nivelAcesso, String senha, String username, char inativo) {
        this.idUsuario = idUsuario;
        this.nivelAcesso = nivelAcesso;
        this.senha = senha;
        this.username = username;
        this.inativo = inativo;
    }
    public Usuario(int idUsuario, Funcionario funcionario, int nivelAcesso, String senha, String username, char inativo) {
       this.idUsuario = idUsuario;
       this.funcionario = funcionario;
       this.nivelAcesso = nivelAcesso;
       this.senha = senha;
       this.username = username;
       this.inativo = inativo;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pessoa")
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    
    @Column(name="nivel_acesso", nullable=false)
    public int getNivelAcesso() {
        return this.nivelAcesso;
    }
    
    public void setNivelAcesso(int nivelAcesso) {
        this.nivelAcesso = nivelAcesso;
    }

    
    @Column(name="senha", nullable=false, length=50)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="username", unique=true, nullable=false, length=60)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="inativo", nullable=false, length=1)
    public char getInativo() {
        return this.inativo;
    }
    
    public void setInativo(char inativo) {
        this.inativo = inativo;
    }




}


